# Generated by Django 5.2.8 on 2025-11-24 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('bidang_pembedahan', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraternity', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('period', models.CharField(max_length=20)),
                ('status', models.CharField(default='not_started', max_length=20)),
                ('total_structure', models.FloatField(blank=True, null=True)),
                ('total_process', models.FloatField(blank=True, null=True)),
                ('total_outcome', models.FloatField(blank=True, null=True)),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('fraternity', 'year', 'period')},
            },
        ),
        migrations.CreateModel(
            name='SurgeryActivityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('domain', models.CharField(max_length=255)),
                ('performances_value', models.FloatField()),
                ('target', models.FloatField()),
                ('weight', models.FloatField()),
                ('score', models.FloatField()),
                ('weighted_score', models.FloatField()),
                ('index', models.FloatField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.surgeryactivity')),
            ],
        ),
    ]
