# Generated by Django 5.2.8 on 2026-01-02 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_anaesthesiaactivity_anaesthesiadetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpperGIActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('total_structure', models.FloatField(default=0)),
                ('total_process', models.FloatField(default=0)),
                ('total_outcome', models.FloatField(default=0)),
                ('overall_index', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-period'],
                'unique_together': {('period', 'year')},
            },
        ),
        migrations.CreateModel(
            name='UpperGIDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('domain_name', models.CharField(max_length=255)),
                ('performances_value', models.FloatField(default=0)),
                ('target', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('score', models.FloatField(default=0)),
                ('weighted_score', models.FloatField(default=0)),
                ('index', models.FloatField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accounts.uppergiactivity')),
            ],
            options={
                'unique_together': {('activity', 'category', 'domain_name')},
            },
        ),
    ]
