# Generated by Django 5.2.8 on 2026-01-02 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_uppergiactivity_uppergidetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyTraumaActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('status', models.CharField(default='not_started', max_length=20)),
                ('total_structure', models.FloatField(default=0)),
                ('total_process', models.FloatField(default=0)),
                ('total_outcome', models.FloatField(default=0)),
                ('overall_index', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('period', 'year')},
            },
        ),
        migrations.CreateModel(
            name='EmergencyTraumaDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('domain_name', models.CharField(max_length=255)),
                ('performances_value', models.FloatField(default=0)),
                ('target', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('score', models.FloatField(default=0)),
                ('weighted_score', models.FloatField(default=0)),
                ('index', models.FloatField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.emergencytraumaactivity')),
            ],
        ),
    ]
