# Generated by Django 5.2.8 on 2026-01-02 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emergencytraumaactivity_emergencytraumadetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencytraumaactivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emergencytraumadetail',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accounts.emergencytraumaactivity'),
        ),
        migrations.AlterUniqueTogether(
            name='emergencytraumadetail',
            unique_together={('activity', 'category', 'domain_name')},
        ),
    ]
