# Generated by Django 5.2.8 on 2026-01-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_gscolorectalactivity_gscolorectaldetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anaesthesiadetail',
            name='performances_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='anaesthesiadetail',
            name='target',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emergencytraumadetail',
            name='performances_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emergencytraumadetail',
            name='target',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gscolorectaldetail',
            name='performances_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gscolorectaldetail',
            name='target',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='surgeryactivitydetail',
            name='performances_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='surgeryactivitydetail',
            name='target',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='surgeryactivitydetail',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='uppergidetail',
            name='performances_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uppergidetail',
            name='target',
            field=models.IntegerField(default=0),
        ),
    ]
