# Generated by Django 5.2.8 on 2026-01-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_anaesthesiadetail_performances_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bidang_pembedahan',
            field=models.CharField(blank=True, choices=[('GENERAL SURGERY', 'General Surgery'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('GS COLORECTAL', 'GS Colorectal'), ('EMERGENCY & TRAUMA', 'Emergency & Trauma'), ('ANAESTHESIA', 'Anaesthesia'), ('UPPER GI', 'Upper GI')], max_length=255, null=True),
        ),
    ]
