# Generated by Django 5.2.8 on 2026-08-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_bidang_pembedahan'),
    ]

    operations = [
        migrations.AddField(
            model_name='anaesthesiadetail',
            name='denominator',
            field=models.IntegerField(default=0),
        ),
    ]
