# Generated by Django 5.2.8 on 2026-08-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_anaesthesiadetail_denominator'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgeryactivitydetail',
            name='denominator',
            field=models.IntegerField(default=0),
        ),
    ]
