# Generated by Django 5.2.8 on 2026-09-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_surgeryactivitydetail_denominator'),
    ]

    operations = [
        migrations.AddField(
            model_name='gscolorectaldetail',
            name='denominator',
            field=models.IntegerField(default=0),
        ),
    ]
