# Generated by Django 5.2.8 on 2026-09-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_gscolorectaldetail_denominator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bidang_pembedahan',
            field=models.CharField(blank=True, choices=[('GENERAL SURGERY', 'General Surgery'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('GS COLORECTAL', 'GS Colorectal'), ('EMERGENCY & TRAUMA', 'Emergency & Trauma'), ('ANAESTHESIA', 'Anaesthesia'), ('UPPER GI', 'Upper GI'), ('GENERAL SURGERY BREAST AND ENDOCRINE', 'General Surgery Breast and Endocrine'), ('GENERAL SURGERY VASCULAR', 'General Surgery Vascular'), ('GENERAL SURGERY HEPATOBILIARY', 'General Surgery Hepatobiliary'), ('GENERAL SURGERY THORACIC', 'General Surgery Thoracic'), ('CARDIOTHORACIC SURGERY', 'Cardiothoracic Surgery')], max_length=255, null=True),
        ),
    ]
